# Here you can specify default options for TinyMCE across all controllers
#
# theme: advanced
# plugins:
#  - table
#  - fullscreen
theme: advanced
editor_selector: mceEditor2
width: 550px
height: 220px
theme_advanced_resizing: true
theme_advanced_toolbar_location: top
theme_advanced_toolbar_align: left
theme_advanced_buttons1:
    - fullscreen
    - separator
    - bold
    - italic
    - underline
    - strikethrough
    - separator
    - undo
    - redo
    - separator
    - link
    - unlink
    - template
    - formatselect
    - code
theme_advanced_buttons2:
    - cut
    - copy
    - paste
    - separator
    - pastetext
    - pasteword
    - separator
    - bullist
    - numlist
    - outdent
    - indent
    - separator
    - justifyleft
    - justifycenter
    - justifyright
    - justifiyfull
    - separator 
    - removeformat
    - charmap
plugins:
    - contextmenu
    - paste
    - media
    - fullscreen
    - template
    - noneditable
template_external_list_url: /templates/templates.js
noneditable_leave_contenteditable: true
theme_advanced_blockformats: p,h1,h2,h3,h4,h5,h6